### ISSUE TITLE
Manifests on release branches (tackle-k8s) reference :latest.

### ISSUE THREAD

**Issue by jortel** [konveyor/operator#268]
```
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: konveyor
  namespace: konveyor-tackle
spec:
  displayName: Konveyor Operator
  publisher: Konveyor
  sourceType: grpc
  image: quay.io/konveyor/tackle2-operator-index:latest
```
