### ISSUE TITLE
:bug: The generic extension need to be split into separate provider extensions.

### ISSUE THREAD

**Issue by jortel** [konveyor/operator#399]
The generic extension need to be split into separate provider extensions.

Python extension:
```yaml
kind: Extension
metadata:
  name: python
  namespace: konveyor-tackle
spec:
  addon: analyzer
  container:
    args:
    - --port
    - $(PORT)
    env:
    - name: PORT
      value: ${seq:8000}
    image: quay.io/konveyor/generic-external-provider:latest
    imagePullPolicy: Always
    name: java
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 1
        memory: 1Gi
  metadata:
    provider:
      address: localhost:$(PORT)
      initConfig:
      - providerSpecificConfig:
          lspServerName: generic
          lspServerPath: /usr/local/bin/pylsp
          workspaceFolders:
          - $(builtin.location)
          dependencyFolders:
          - examples/python/__pycache__ 
          - examples/python/.venv
      name: python
  selector: tag:Language=Python
```
TypeScript (node.js) extension:
```yaml
apiVersion: tackle.konveyor.io/v1alpha1
kind: Extension
metadata:
  name: nodejs
  namespace: konveyor-tackle
spec:
  addon: analyzer
  container:
    args:
    - --port
    - $(PORT)
    env:
    - name: PORT
      value: ${seq:8000}
    image: quay.io/konveyor/generic-external-provider:latest
    imagePullPolicy: Always
    name: java
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 1
        memory: 1Gi
  metadata:
    provider:
      address: localhost:$(PORT)
      initConfig:
        providerSpecificConfig:
          lspServerName: generic
          lspServerPath: /usr/local/bin/typescript-language-server
          lspServerArgs:
          - "--stdio"
          workspaceFolders:
          - $(builtin.location)
      name: nodejs
  selector: tag:Language=TypeScript
```
